

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ai
    username: postgres
    password: 123456
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.1
    vectorstore:
      pgvector:
      index-type: HNSW
      distance-type: COSINE_DISTANCE
      dimensions: 1536
      max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
# 解决乱码
server:
  servlet:
    encoding:
      force: true
      charset: UTF-8

#打开日志
logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG
